name: Data science lab
description: Scientific updates on knowledge representation, reasoning and recommendation from the Data Science lab at the Dong-A University
#url: https://datascience-labs.github.io/
url: https://www.datasciencelabs.org
baseurl: ''

markdown: kramdown
permalink: /:categories/:title/
future: true
sass:
  sass_dir: css

plugins: ['jekyll-twitter-plugin']

exclude:
  - "*.branches"
  - "*.class"
  - "*.cpp"
  - "*.csv"
  - "*.fasta"
  - "*.gz"
  - "*.h"
  - "*.hh"
  - "*.ipynb"
  - "*.jar"
  - "*.java"
  - "*.kml"
  - "*.log"
  - "*.mcc"
  - "*.nb"
  - "*.newick"
  - "*.nex"
  - "*.py"
  - "*.R"
  - "*.rb"
  - "*.Rmd"
  - "*.tiff"
  - "*.tips"
  - "*.trees"
  - "*.tsv"
  - "*.txt"
  - "*.xml"
  - "*.zip"
  - "Gemfile"
  - "Gemfile.lock"

projects:
  - "datascience-labs/debs2022gc"
  - "datascience-labs/Green-Car-Charging-Station-Site-Selection"
  - "datascience-labs/Data_Analytics_for_Age_friendly_busan"
  - "datascience-labs/Balance_Up"
  - "datascience-labs/Carbon-friendly"
  - "datascience-labs/COCL"
  - "datascience-labs/FDIA_with_TCN"
  - "datascience-labs/anomali-flow"